// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnTLSJ_7e752tkL524_owultZJpAUAQng',
    appId: '1:30199814832:web:de6bcc3bf4c3a57b207975',
    messagingSenderId: '30199814832',
    projectId: 'vocal-looper-app',
    authDomain: 'vocal-looper-app.firebaseapp.com',
    storageBucket: 'vocal-looper-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUDdm-YZ1pyPfdssNwjzMoqBZjj7Ame-g',
    appId: '1:30199814832:android:078d646d71470b4e207975',
    messagingSenderId: '30199814832',
    projectId: 'vocal-looper-app',
    storageBucket: 'vocal-looper-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0FSMwNjAtrIwcXAmlFgqsrACMyECnMBw',
    appId: '1:30199814832:ios:652f28e1ccbcd3ec207975',
    messagingSenderId: '30199814832',
    projectId: 'vocal-looper-app',
    storageBucket: 'vocal-looper-app.firebasestorage.app',
    iosBundleId: 'com.example.vocalLooperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0FSMwNjAtrIwcXAmlFgqsrACMyECnMBw',
    appId: '1:30199814832:ios:652f28e1ccbcd3ec207975',
    messagingSenderId: '30199814832',
    projectId: 'vocal-looper-app',
    storageBucket: 'vocal-looper-app.firebasestorage.app',
    iosBundleId: 'com.example.vocalLooperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnTLSJ_7e752tkL524_owultZJpAUAQng',
    appId: '1:30199814832:web:427492bea11ecf54207975',
    messagingSenderId: '30199814832',
    projectId: 'vocal-looper-app',
    authDomain: 'vocal-looper-app.firebaseapp.com',
    storageBucket: 'vocal-looper-app.firebasestorage.app',
  );
}
